### ISSUE TITLE
Implement readiness and liveness probes

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#155]
Implementation proposal:

1. Add a section on application's values.yaml specifying the probe http address:

```yaml
harness:
   readinessProbe:
        path: /api/ready
   livenessProbe:
        path: /api/live
```

2. Add the api paths and default implementation to harness-application generator.

The application developer will be able to implement the desired logic in readiness and liveness probes, keeping in mind the risks of using the probes to manage dependencies: https://blog.colinbreck.com/kubernetes-liveness-and-readiness-probes-how-to-avoid-shooting-yourself-in-the-foot/#kuberneteslivenessandreadinessprobes
