### ISSUE TITLE
Auto config map creation in deployments

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#197]
Some applications need configuration files that may or not depend on helm values.

Now we already support resources directory, but we are not automatically loading that resources on a config map.

An example of that can be found on accounts application loading realm.json

```json
{
        "id": {{ .Values.namespace | quote }},
        "realm": {{ .Values.namespace | quote }},
        "enabled": true,
        "sslRequired": "external",
...
```
This is loaded inside a config map like

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.accounts.name | quote }}
  labels:
    app: {{ .Values.apps.accounts.name | quote }}
{{ include "deploy_utils.labels" $ | indent 4 }}
data:
  realm.json: {{ tpl (.Files.Get "resources/accounts/realm.json") . | quote }}
```

and loaded on a volume like:

```yaml
spec:
 template:
  spec:
     containers:
        volumeMounts:
        - name: realm-config
          mountPath: "/tmp/realm.json"
          subPath: realm.json

      volumes:
      - name: realm-config
        configMap:
          name: {{ .Values.apps.accounts.name | quote }}
```

It would be nice to do all of this in the values.yaml file like:

```yaml
harness:
   resources:
      - src: realm.json
      - dest: /tmp/realm.json
```

**Comment by lrebscher** [comment]
Important to know:
>  A container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates.
 https://kubernetes.io/docs/concepts/storage/volumes/
 
 We cannot use subPath here, but we don't have to, since the key name of the data entry in the configmap is used as filename: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap . But have to try this out first.

There is also the option to create only one ConfigMap that stores all resources files as shown here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  SPECIAL_LEVEL: {{ tpl (.Files.Get "resources/samples/example.json") . | quote }}
  SPECIAL_TYPE: {{ tpl (.Files.Get "resources/accounts/exampleB.json") . | quote }}
```

And store all of them in a single directory so that we have some conventions where user might find their created config files.
