### ISSUE TITLE
Improve development tools: skaffold and in-cluster debugging

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#199]
One of the main struggles of the micro-services pattern followed by cloudharness is the difficulty in developing and debugging application.

Skaffold is a tool that implements smart build-update of images in k8s and enables in-cluster debugging.

**Comment by filippomc** [comment]
First successful attempt with Python/Flask backend.


### Deploy as usual in minikube or in the remote cluster

1. Set up kubectl 
1. Run `harness-deployment ... --deploy`

### Install Skaffold
Download and install as in https://skaffold.dev/docs/install/

### Initialize Skaffold 
Can use any Python harness application (e.g applications/samples).

#### Add k8s definition for your application root

Add a file k8s-app.yaml with the following content:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspaces
spec:
  selector:
    matchLabels:
      app: workspaces
  template:
    metadata:
      labels:
        app: workspaces
    spec:
      containers:
      - name: workspaces
        image: workspaces
        command: ["python"]
        args:  ["/usr/src/app/samples/__main__.py"]
        ports:
          - containerPort: 8080
```

It is important to override the command: Skaffold debugger can connect only to plain python command such as a flask run application, like (file __main__.py);

```python
if __name__ == "__main__":
    connexion_app.app.run(port=8080)

```
#### Initialize skaffold 

Run `skaffold init`.
If everything is ok, you'll be prompted to choose the Docker files to be handled by Skaffold, ending up with something like:

```yaml
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: samples
build:
  artifacts:
  - image: samples
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-app.yaml
```

#### Run dev with skaffold
At this point, we can run `skaffold dev --namespace [MY_NAMESPACE]--default-repo [MY_REGISTRY]`.

After this command, Skaffold will be listening for changes inside samples application and update the deployment on those changes.

### Configure vs code for debugging

#### Install cloud code extension
Follow the instructions in this page: https://cloud.google.com/code/docs/vscode/quickstart-local-dev#installing

#### Set up a "Run on kubernetes" run configuration
Follow instructions on this page: https://cloud.google.com/code/docs/vscode/quickstart-local-dev#debugging_your_app

Configure the run config to match your registry and paths
The launch.json wil look like this:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Kubernetes: Run/Debug",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/skaffold.yaml",
            "watch": true,
            "cleanUp": false,
            "portForward": true,
            "imageRegistry": "localhost:5000",
            "debug": [
                {
                    "image": "workspaces",
                    "sourceFileMap": {
                        "${workspaceFolder}/backend": "/usr/src/app"
                    }
                }
            ]
        }
    ]
}

```
