### ISSUE TITLE
Override command/args in auto deployment

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#200]
Allowing to change the command for deployments is a useful feature to reuse the same image in different environments and runtimes.

Simply add the values to the harness/deployment section on application's values.yaml

```yaml
harness:
   deployment:
      auto: true
      command: ["python"]
      args: ["__main__.py"]
```
