### ISSUE TITLE
Add condition to codefresh prod yaml for the approval step

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#231]
Would be nice if the approval step also has a condition
e.g.
```
      condition:
        all:
          whenVarExists: includes("${{DEPLOYMENT_PUBLISH_TAG}}", "{{DEPLOYMENT_PUBLISH_TAG}}")
            == false
          whenVarExists2: includes("${{REPO_TOKEN}}", "{{REPO_TOKEN}}") == false
```
either in stage or in prod it will automatically skip this step
