### ISSUE TITLE
Disable the database backup cron job generation when backup == false

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#235]
When I set backup to false I still see the cron jobs for the database backup being generated
this should not be done

![image](https://user-images.githubusercontent.com/124044/108824371-ea00f000-75c1-11eb-88c2-454d26a3e683.png)

```
.../ifn/ifn$ cat deployment-configuration/values-template.yaml 
tls: ifn-metacell-us-tls
namespace: ifn
mainapp: mnp-ifn
backup:
   active: false
```
in the values.yaml the back is set to true
```
grep -A 2 -B 2 -i backup deployment/helm/values.yaml 
  letsencrypt:
    email: filippo@metacell.us
backup:
  active: true
  keep_days: '7'
--
  schedule: '@daily'
  suffix: .gz
  dir: /backups
  resources:
    requests:
```
may be the overwrite doesn't work
