### ISSUE TITLE
Handle secrets

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#240]
Helm overrides secrets values, so secrets cannot be included in the deployment unless we provide secrets values directly in the deployment itself.

Possible solutions:

- Include secrets to the deployment as parameters. These parameters may have a default value and can be set as variables in the codefresh deployment
- Use helm lookup functionality to include the secret if does not exist.

**Comment by filippomc** [comment]
Example lookup:

```yaml
{{- if not (lookup "v1" "Secret" .Values.namespace "my-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Mail credentials need to be set manually by the sys admin
  a: Q0hBTkdFTUU=
  b: Q0hBTkdFTUU=
  c: Q0hBTkdFTUU=
{{- end }}
```

**Comment by filippomc** [comment]
Integration with Codefresh variables is important: we use the values coming from codefresh to set secrets

**Comment by filippomc** [comment]
Harness deployment allows to specify the secrets. Using a .env file would allow to specify secret inside the pipeline and also on local deployment

**Comment by zsinnema** [comment]
if we let helm manage the secrets then we always need to run a deployment in case we want to change the value of the secret.
not sure if this is the best way to do

e.g. if a MNP Checkout stripe token is changed (because of reasons) we need to run the whole pipeline to get the secret where it resides in to get deployed. this sounds strange and not logical to me

question: why not have "default" secrets created via helm (as above shown) and don't let an automated process touch them anymore

**Comment by filippomc** [comment]
The way I'd interpret deployment set secret is as default values. With the lookup we can ensure that secrets don't get overridden after the first deploy

**Comment by filippomc** [comment]
After some tests I think this can be a good strategy:

- Secrets are managed automatically by cloudharness, as deployments, services, etc. Secret values come from values.yaml
- The deployment pipeline sets default values for all secrets using variables, with something like:

```yaml
  deployment:
    stage: deploy
    image: codefresh/cfstep-helm:3.4.1
    title: Installing chart
    environment:
      - CHART_REF=./deployment/helm
      - RELEASE_NAME=${{NAMESPACE}}
      - KUBE_CONTEXT=${{CLUSTER_NAME}}
      - NAMESPACE=${{NAMESPACE}}
      - CHART_VERSION=${{DEPLOYMENT_PUBLISH_TAG}}
      - HELM_REPO_USE_HTTP=false
      - HELM_REPO_CONTEXT_PATH=
      - TIMEOUT=600s
      - VALUESFILE_values=./deployment/helm/values.yaml
    custom_values:
      - 'app_workspaces_github_token=${{GITHUB_TOKEN}}'
      - 'app_workspaces_github_user=${{GITHUB_USER}}'
```

- The secret values need to be removed from the configmap that contains all values
- Secrets can be changed through k8s api, so:
  - use lookup to avoid overriding secrets in pipelines
  - write the logic so that the secret is always read on runtime (otherwise need to restart pods after changing secrets)
