### ISSUE TITLE
Improve customization of auto generated configuration

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#25]
The default behaviour is using the app name (in turn taken from the folder name) to define the image name, deployment name, service name.
This is fine for the use case in which the same application is defining image, deployment, service but doesn't allow for example to:

- define a custom external image
- connect the service to a custom deployment
- create an ingress to an external service

With this feature, we want to potentially override all these values, maintaining the default behaviour which falls back to the app name. The app name itself should be allowed to be customized

We want to also to transition the place where harness configuration is stored in the `values.yaml` file from the root to a `harness` key-map.

Old values.yaml:

```yaml
name: portal (auto set)
subdomain: www
image: portal (auto set)
replicas: 1
port: 8081
secureme: false
autoservice: true
autodeploy: true
resources:
  requests:
    memory: 32Mi
    cpu: 25m
  limits:
    memory: 64Mi
    cpu: 50m
```

New values.yaml exampel:

```yaml

harness:
  name: portal
  subdomain: www (optional, created ingress)
  secured: true
  deployment:
    auto: false
    replicas: 1
    image: nginx (if set, this image will be used in the auto deployment set for the application)
    name: proxy-deployment
    port: 8081
    resources:
      requests:
        memory: 32Mi
          cpu: 25m
        limits:
          memory: 64Mi
          cpu: 50m
  service:
    auto: true
    name: portal-service
    port: 80
```

Old specifications must continue working.
