### ISSUE TITLE
Create Python api to retrieve infrastructure information

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#33]
The idea behind this is to give some applications the capability to make configurations depending on other applications in the cluster.

Information comes from the harness section of the values file. Example
```yaml
apps:
  workflows:
    harness:
      name: workflows
      subdomain: workflows
      domain: null
      secured: false
      deployment:
        auto: false
        replicas: 1
        image: localhost:5000/workflows:2
        name: workflows
        port: 8081
        resources: &id001
          requests:
            memory: 32Mi
            cpu: 25m
          limits:
            memory: 500Mi
            cpu: 500m
      service:
        auto: true
        name: workflows
        port: 8080
      deploy:
        auto: true
        port: 8080
    image: localhost:5000/workflows:2
    name: workflows
    port: 8081
    resources: *id001
```

Sample usage
```python
from harness import applications
app_conf = applications.get_configurations()
for app in app_conf:
    if app['deployment']['auto']:
        # DO SOMETHING
```

The values.yaml file can be injected in a configmap like this:
```yaml
kind: ConfigMap
apiVersion: v1
data:
  allvalues.yaml: |
    {{- .Values | toYaml | nindent 4 }}
```
This configmap can be used inside auto-deployments.yaml to be injected inside every automatic deployment.
