### ISSUE TITLE
Replace helm variables on mounted files

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#382]
At the moment it is possible to mount files on pods like this: https://github.com/MetaCell/cloud-harness/blob/master/applications/samples/deploy/values.yaml#L23

It would be nice to add an option to use variables replacement from the helm values

```
harness:
  resources:
    - name: my-config
      src: "myConfig.json"
      dst: "/tmp/resources/myConfig.json"
      replacements: true
```

myConfig.json:
```
{
  "name": {{ .Values.apps.samples.myvariable }}
}
```
