### ISSUE TITLE
Environment inheritance

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#444]
Say we have one application with:

```
values.yaml
values-dev.yaml
values-local.yaml
```

It would be nice to load the three in sequence when I specify `-e dev-local`

**Comment by filippomc** [comment]
Another option would be to give the possibility to specify environments hierarchy as a general configuration, like:

```yaml
environments:
- name: dev
  derived:
  - test
  - local
- name: prod
  derived:
  - staging
```

With this strategy, we lose some freedom but we gain in making clearer expectations on what's in the deployment
