### ISSUE TITLE
Add support for persistent volume to auto deployed application

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#45]
It would be nice to have an option in the values.yaml of an application to define a persistent volume.

E.g.
```
  deployment:
    auto: true
    ....
    volume:
      name: persistent-volume-name
      size: 4G
      mountpath: /usr/src/app/static/persistent-files
```
