### ISSUE TITLE
Allow for multiple ports for deployments and services

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#463]
Only one port can be specified now for deployments and services.
This covers most of the cases and gives simplicity but some applications may want to expose multiple ports.

I'd like to treat it as an edge case rather than the default, as for really special cases custom k8s templates can be used.

Something like:

```yaml
harness:
  deployment:
     ...
     port: 80
     additionalPorts:
     - 8080
     - 9000
```
