### ISSUE TITLE
Define test users pool

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#483]
At the moment, the only way to define a new user is to add the user from the Keycloak interface.
This is enough for most of the use cases, but having a default user pool would help on automated end-to-end testing (see also #248), as logging into the system and checking the permissions is the base of most tests.

As these users are defined for testing, there is no need to use secure credentials.

An implementation could be to add users to the accounts application values-*.yaml:

```yaml
harness:
   users:
   - username: a
     password: test
     roles:
     - admin
     clientRoles:
     - myclientrole
```
