### ISSUE TITLE
Implement image overriding 

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#55]
In the case an application overrides another application, if no overriding docker image is defined, there is no way to override files added during the build. A common use case for this is changing the theme (e.g. a logo, a css, file), but it also would be useful to override code.

For instance take the following structure:

- applications
  - accounts
     - theme
- cloud-harness
  - applications
    - accounts
       - Dockerfile
       - theme
       - ...

What we can do now is to override the Dockerfile and do anything needed there, but that requires to copy the whole content.
- applications
  - accounts
     - Dockerfile
     - theme
     - ...
- cloud-harness
  - applications
    - accounts
       - Dockerfile
       - theme
       - ...

Another option is to base the image on the previously built image defining explicitly the dependency on the Dockerfile and then copying the theme, like:

```
ARG REGISTRY
ARG TAG=latest
FROM ${REGISTRY}accounts:${TAG}

COPY theme .
```

Desired outcome is that any file we change in the overriding folder is used in replacement of the original file.
A solution for this is to merge the directories in a temporary folder before actually performing the build, and use that folder as context for the image build.

This must be implemented consistently for the codefresh and the scripted build.

**Comment by filippomc** [comment]
Need to improve this in order to work on codefresh. In case of overriding, both images have to be built, with precedence on the image coming from cloudharness.

Example with jupyterhub overriding:
```yaml
version: '1.0'
stages:
- prepare
- build
- deploy
steps:
  main_clone:
     ...
  post_main_clone:
     ...
  prepare_deployment:
    ...
  prepare_deployment_view:
    ...
  build_base_images:
     ...
  build_cloudharness_images:
    type: parallel
    stage: build
    steps:
      ...
      jupyterhub:
        type: build
        stage: build
        tag: ${{CF_REVISION}}
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_REVISION}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: ${{CODEFRESH_REGISTRY}}
        no_cf_cache: false
        image_name: jupyterhub
        title: Jupyterhub
        working_directory: ./cloud-harness/applications/jupyterhub
     ...
  build_application_images:
    type: parallel
    stage: build
    steps:
      ...
      jupyterhub:
        type: build
        stage: build
        tag: ${{CF_REVISION}}
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_REVISION}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: ${{CODEFRESH_REGISTRY}}
        no_cf_cache: false
        image_name: jupyterhub
        title: Jupyterhub 
        working_directory: ./applications/jupyterhub
  deployment:
    ...
```
