### ISSUE TITLE
Add support to use multiple database templates on application creation

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/cloud-harness#559]
Running:
```
harness-application clockdate -t server -t db-postgres -t db-neo4j
```
Results in:
```
harness:
  database: {auto: true, type: neo4j}
  dependencies:
    build: [cloudharness-base, cloudharness-flask]
  deployment: {auto: true, port: 8080}
  livenessProbe: {path: /api/live}
  readinessProbe: {path: /api/ready}
  secured: false
  service: {auto: true, port: 8080}
  subdomain: clockdate
  ```

Expected:
Generates an application with 2 databases
