### ISSUE TITLE
Choose storage class and write mode for auto volumes

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#597]
- [ ] Auto-deployment volumes
- [ ] Workflow volumes
- [ ] Jupyterhub volumes (probably already available, have to check and test)

This connects to the possibility to use ManyToMany writing and provisioning

## Auto deployment

Now:

```yaml
volume:
   name: myFirstVolume
   mountpath: /usr/src/app/myvolume
   auto: true
   size: 5Gi
```

Then:
```yaml
volume:
   name: myFirstVolume
   mountpath: /usr/src/app/myvolume
   auto: true
   size: 5Gi
   storageclass: mystorageclass
   mode: ManyToMany
```
