### ISSUE TITLE
Basic user quotas

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#637]
Implement basic application user quotas based on Keycloak user / group attributes

base quotas are stored in the application in the `values.yaml` within the `harness` tree
the application can get the quotas and responds according to the quotas

example for Jupyterhub
```
harness:
  quotas:
    # sets the maximum number of workspaces for the user
    quota-ws-max: 5
    # sets the maximum number of workspaces open concurrently
    quota-ws-open: 3
    # sets the cpu guaranteed on a single workspace
    quota-ws-guaranteedcpu: 1
    # sets the cpu limit on a single workspace
    quota-ws-maxcpu: 1
    # sets the memory guaranteed on a single workspace
    quota-ws-guaranteedmem: 1
    # sets the memory limit on a single workspace
    quota-ws-maxmem: 1.5G
    # sets the storage dedicated to the user data
    quota-storage-max: 1G
...
```
