### ISSUE TITLE
Basic Jupyterhub user quotas

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#638]
Implement basic Jupyterhub user quotas based on Keycloak user / group attributes

use: #637 for implementation

Jupyterhub (workspaces) quotas:
```
    # sets the maximum number of workspaces open concurrently
    quota-ws-open:
    # sets the cpu guarantee on a single workspace in CPU units
    quota-ws-guaranteecpu:
    # sets the cpu limit on a single workspace in CPU units
    quota-ws-maxcpu:
    # sets the memory guarantee on a single workspace in Gb units
    quota-ws-guaranteemem:
    # sets the memory limit on a single workspace in Gb units
    quota-ws-maxmem:
    # sets the storage dedicated to the user data in Gb units
    quota-storage-max:
```

example:
```
harness:
  quotas:
    quota-ws-open: 3
    quota-ws-guaranteecpu: 0.25
    quota-ws-maxcpu: 1.5
    quota-ws-guaranteemem: 0.128
    quota-ws-maxmem: 1.024
    quota-storage-max: 1
...
```
