### ISSUE TITLE
Wrong skaffold.yaml "overrides" section generation in some cases

### ISSUE THREAD

**Issue by aranega** [MetaCell/cloud-harness#697]
The `overrides` section generated by CH of the `skaffold.yaml` file is not generated properly if the folder that contains the `Dockerfile` of a task/workflow also contains a virtualenv or additional python code.

The piece of code that [generates the `overrides` section](https://github.com/MetaCell/cloud-harness/blob/685f83b289ab40eefc217e6202dbdcfa33628fd0/tools/deployment-cli-tools/ch_cli_tools/skaffold.py#L141) relies on the presence of a `__main__.py` file located in a directory or sub-directory of where the `Dockerfile` of a task is located. If there is a virtualenv or any other code there that is used for testing purpose only (in local env), the generated `skaffold.yaml` file could contain bad assertions.
Here is an example of what was generated in my env as I have virtualenv to test some workflows faster:

```yaml
overrides:
        apps:
          common:
            harness:
              deployment:
                args: [/usr/src/app/common/__main__.py]
                command: [python]
          coregistration:
            harness:
              deployment:
                args: [/usr/src/app/matplot/__main__.py]
                command: [python]
          portal:
            harness:
              deployment:
                args: [/usr/src/app/IPython/__main__.py]
                command: [python]
          workflows:
            harness:
              deployment:
                args: [/usr/src/app/workflows_api/__main__.py]
                command: [python]
```

We can see that, at least, `coregistration` and `portal` are not generated properly.

This comes from a bad identification of the `flask_main` file, relying only on the file name is not enough, the content of the file must be inspected as well, even if that's not bullet proof, at least, that could limit false positive detections.
