### ISSUE TITLE
Specific gatekeeper configuration

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#82]
Need to specify the gatekeeper mapping

```
harness:
   secured: true
   uri_role_mapping:
    - uri: /admin/test
      methods:
      - GET
      roles:
      - openvpn:vpn-user
      - openvpn:prod-vpn
      - test
  - uri: /admin/*
      methods:
      - GET
      roles:
      - openvpn:vpn-user
      - openvpn:commons-prod-vpn
```

the role_mapping section is copied inside the resource section in auto-gatekeeper
